<template>
  <div id="app">
    <div id="top-box" class="fade-in-fwd">
      <div id="nav" class="text-focus-in">
        <span class="header title-pink">信息高速公路</span>
        <span class="header">暢通無阻全球資訊網</span>
        <span class="header">萬物互聯</span>
        <span class="header title-yellow">因特網内容提供服務中國互聯網</span>
        <span class="header">服務供應</span>
        <span class="header title-orange">贊大佬</span>
        <span class="header">實在太强了</span>

        <div id="router-links">
          <router-link to="/">主頁</router-link> |
          <router-link to="/about">爲什麽設置這個頁面</router-link>
        </div>
      </div>
    </div>
    <div id="bottom-box">
      <transition :name="slider" mode="out-in">
        <router-view />
      </transition>
    </div>
  </div>
</template>

<script>
export default {
  data () {
    return {
      slider: ''
    }
  },
  watch: {
    '$route' (to, from) {
      const toDepth = to.path.split('/').filter(n => n).length
      const fromDepth = from.path.split('/').filter(n => n).length
      this.slider = toDepth < fromDepth ? 'slide-right' : 'slide-left'
    }
  }
}
</script>

<style>
@import url("https://fonts.googleapis.com/css?family=Rubik&display=swap");

html,
body {
  padding: 0px 0px;
  margin: 0px 0px;
  background: #32547b;
  height: 100%;
}

#app {
  font-family: Rubik, Helvetica, Arial, Noto Sans CJK SC, Sarasa Gothic SC,
    Microsoft YaHei, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  color: #ffffff;
}

#top-box {
  height: 80vh;
  background: #154165;
  display: flex;
  flex-direction: column;
  flex-wrap: nowrap;
  justify-content: center;
  align-items: center;
  align-content: center;
}

#nav {
  margin: 0px auto;
  max-width: 900px;
  padding-left: 10px;
  padding-right: 10px;
}

#nav a {
  font-weight: bold;
  color: #ffffff;
}

#nav a.router-link-exact-active {
  color: #eae7af;
}

.header {
  font-family: Nova Mono, Helvetica, Arial, Noto Sans CJK SC, Sarasa Gothic SC,
    Microsoft YaHei, sans-serif;
  font-weight: bold;
  font-size: 3.7rem;
  color: rgba(255, 255, 255, 0.5);
}

.title-pink {
  color: #eab0d9;
}

.title-yellow {
  color: #eae7af;
}

.title-orange {
  color: #d65a31;
}

#router-links {
  margin-top: 2rem;
}

#bottom-box {
  max-width: 900px;
  margin: 0px auto;
  padding-left: 10px;
  padding-right: 10px;
}

.fade-in-fwd {
  -webkit-animation: fade-in-fwd 0.3s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  animation: fade-in-fwd 0.3s cubic-bezier(0.39, 0.575, 0.565, 1) both;
}

.text-focus-in {
  -webkit-animation: text-focus-in 0.5s cubic-bezier(0.55, 0.085, 0.68, 0.53)
    both;
  animation: text-focus-in 0.5s cubic-bezier(0.55, 0.085, 0.68, 0.53) both;
}

.slide-left-enter-active,
.slide-left-leave-active,
.slide-right-enter-active,
.slide-right-leave-active {
  transition-duration: 0.5s;
  transition-property: height, opacity, transform;
  transition-timing-function: cubic-bezier(0.55, 0, 0.1, 1);
  overflow: hidden;
}

.slide-left-enter,
.slide-right-leave-active {
  opacity: 0;
  transform: translate(2em, 0);
}

.slide-left-leave-active,
.slide-right-enter {
  opacity: 0;
  transform: translate(-2em, 0);
}

/* ----------------------------------------------
 * Generated by Animista on 2020-2-27 15:27:28
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in-fwd
 * ----------------------------------------
 */
@-webkit-keyframes fade-in-fwd {
  0% {
    -webkit-transform: translateZ(-80px);
    transform: translateZ(-80px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateZ(0);
    transform: translateZ(0);
    opacity: 1;
  }
}
@keyframes fade-in-fwd {
  0% {
    -webkit-transform: translateZ(-80px);
    transform: translateZ(-80px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateZ(0);
    transform: translateZ(0);
    opacity: 1;
  }
}

@-webkit-keyframes text-focus-in {
  0% {
    -webkit-filter: blur(12px);
    filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0px);
    filter: blur(0px);
    opacity: 1;
  }
}
@keyframes text-focus-in {
  0% {
    -webkit-filter: blur(12px);
    filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0px);
    filter: blur(0px);
    opacity: 1;
  }
}
</style>
