<template>
  <div id="app">
    <div id="top-box" class="fade-in-fwd">
      <div id="nav" class="text-focus-in">
        <span id="title1" class="header">信息高速公路</span>
        <span id="title2" class="header">暢通無阻全球資訊網</span>
        <span id="title3" class="header">萬物互聯</span>
        <span id="title4" class="header">因特網内容提供服務中國互聯網</span>
        <span id="title5" class="header">服務供應</span>
        <span id="title6" class="header">贊大佬</span>
        <span id="title7" class="header">實在太强了</span>

        <div id="router-links">
          <router-link to="/">主頁</router-link> |
          <router-link to="/about">爲什麽設置這個頁面</router-link>
        </div>
      </div>
    </div>
    <div id="bottom-box">
      <router-view />
    </div>
  </div>
</template>

<style>
@import url("https://fonts.googleapis.com/css?family=Rubik&display=swap");

html,
body {
  padding: 0px 0px;
  margin: 0px 0px;
  background: #32547b;
  height: 100%;
}

#app {
  font-family: Rubik, Helvetica, Arial, Noto Sans CJK SC, Sarasa Gothic SC,
    Microsoft YaHei, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  color: #ffffff;
}

#top-box {
  height: 80vh;
  background: #154165;
  display: flex;
  flex-direction: column;
  flex-wrap: nowrap;
  justify-content: center;
  align-items: center;
  align-content: center;
}

#nav {
  margin: 0px auto;
  max-width: 900px;
  padding-left: 10px;
  padding-right: 10px;
}

#nav a {
  font-weight: bold;
  color: #ffffff;
}

#nav a.router-link-exact-active {
  color: #eae7af;
}

.header {
  font-family: Nova Mono, Helvetica, Arial, Noto Sans CJK SC, Sarasa Gothic SC,
    Microsoft YaHei, sans-serif;
  font-weight: bold;
  font-size: 3.7rem;
  color: rgba(255, 255, 255, 0.5);
}

#title1 {
  color: #eab0d9;
}

#title4 {
  color: #eae7af;
}

#title6 {
  color: #d65a31;
}

#router-links {
  margin-top: 2rem;
}

#bottom-box {
  max-width: 900px;
  margin: 0px auto;
  padding-left: 10px;
  padding-right: 10px;
}

.fade-in-fwd {
  -webkit-animation: fade-in-fwd 0.3s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  animation: fade-in-fwd 0.3s cubic-bezier(0.39, 0.575, 0.565, 1) both;
}

.text-focus-in {
  -webkit-animation: text-focus-in 0.5s cubic-bezier(0.55, 0.085, 0.68, 0.53)
    both;
  animation: text-focus-in 0.5s cubic-bezier(0.55, 0.085, 0.68, 0.53) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2020-2-27 15:27:28
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in-fwd
 * ----------------------------------------
 */
@-webkit-keyframes fade-in-fwd {
  0% {
    -webkit-transform: translateZ(-80px);
    transform: translateZ(-80px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateZ(0);
    transform: translateZ(0);
    opacity: 1;
  }
}
@keyframes fade-in-fwd {
  0% {
    -webkit-transform: translateZ(-80px);
    transform: translateZ(-80px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateZ(0);
    transform: translateZ(0);
    opacity: 1;
  }
}

@-webkit-keyframes text-focus-in {
  0% {
    -webkit-filter: blur(12px);
    filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0px);
    filter: blur(0px);
    opacity: 1;
  }
}
@keyframes text-focus-in {
  0% {
    -webkit-filter: blur(12px);
    filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0px);
    filter: blur(0px);
    opacity: 1;
  }
}
</style>
